export const AVAILABLE_TAGS = [
  "Bicycle & Pedestrian",
  "Commission",
  "Economy",
  "Environment",
  "Environment & Energy",
  "Freight & Aviation",
  "grants",
  "Health & Safety",
  "high-frequency",
  "Infrastructure & Utility Services",
  "Livable Communities",
  "Long-Range Plan",
  "SEPTA",
  "Southeastern Pennsylvania Transportation Authority",
  "surface transit",
  "TCDI",
  "TOC",
  "TOD",
  "trackless trolley",
  "Trails",
  "Transit",
  "transit oriented communities",
  "transit-oriented development",
  "transit-supportive",
  "Transportation",
  "Transportation Planning",
  "trolley",
  "Economic Development",
  "Community Planning",
] as const;

export const AVAILABLE_COMMITTEES = [
  { code: "DVGMTF", name: "Delaware Valley Goods Movement Task Force" },
  { code: "HCTF", name: "Healthy Communities Task Force" },
  { code: "IREG", name: "Information Resources Exchange Group" },
  { code: "LUHC", name: "Land Use & Housing Committee" },
  { code: "ME", name: "Municipal Exchange" },
  { code: "PPTF", name: "Public Participation Task Force" },
  { code: "RAC", name: "Regional Aviation Committee" },
  { code: "RSTF", name: "Regional Safety Task Force" },
  { code: "RTC", name: "Regional Technical Committee" },
  { code: "SEP", name: "Sustainable Energy Partnership" },
  { code: "BOARD", name: "The DVRPC Board" },
  { code: "TOTF", name: "Transportation Operations Task Force" },
  { code: "WQMB", name: "Tri-County Water Quality Management Board" },
  { code: "UWAG", name: "Urban Waterfront Action Group" },
] as const;
